# Generated by Django 6.0.3 on 2026-09-26 19:23

import django.db.models.deletion
from django.db import migrations, models


def asignar_empresa_inicial(apps, schema_editor):
    Empresa = apps.get_model('main', 'Empresa')
    Perfil = apps.get_model('account', 'Perfil')
    empresa = Empresa.objects.get(slug='empresa-principal')
    Perfil.objects.filter(empresa__isnull=True).update(empresa=empresa)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_perfil_nro_usuario'),
        ('main', '0002_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='main.empresa'),
        ),
        migrations.RunPython(asignar_empresa_inicial, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='main.empresa'),
        ),
    ]
