# Generated by Django 6.0.3 on 2026-04-14 19:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                null=True,
                config_name="default",
                verbose_name="Descripción",
            ),
        ),
    ]
