# Generated by Django 6.0.3 on 2026-04-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_producto_fecha_creacion_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Cantidad mínima para alerta de bajo stock'),
        ),
    ]
