# Generated by Django 6.0.3 on 2026-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_producto_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciondeposito',
            name='ancho_px',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='configuraciondeposito',
            name='largo_px',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='estanteria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nivel_especifico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
