# Generated by Django 6.0.3 on 2026-09-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_inventario_integridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estanteria',
            options={'permissions': [('view_warehouse', 'Can view warehouse layout'), ('manage_warehouse', 'Can manage warehouse layout')]},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('view_stock', 'Can view stock information'), ('manage_products', 'Can manage products, categories, and suppliers')]},
        ),
    ]
