# Generated by Django 6.0.3 on 2026-09-26 19:23

import django.db.models.deletion
from django.db import migrations, models


def asignar_empresa_inicial(apps, schema_editor):
    Empresa = apps.get_model('main', 'Empresa')
    empresa = Empresa.objects.get(slug='empresa-principal')
    for model_name in ('Producto', 'MovimientosStock'):
        apps.get_model('Stock', model_name).objects.filter(empresa__isnull=True).update(empresa=empresa)


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0007_alter_estanteria_options_alter_producto_options'),
        ('main', '0002_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosstock',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.empresa'),
        ),
        migrations.RunPython(asignar_empresa_inicial, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movimientosstock',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.empresa'),
        ),
    ]
