# Generated by Django 5.0.6 on 2026-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nro_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
