# Generated by Django 6.0.3 on 2026-09-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_cliente_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('access_customer_api', 'Can access the customer lookup API'), ('manage_clients', 'Can create and manage clients')]},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': [('create_sales', 'Can create sales'), ('view_sales', 'Can view own sales'), ('view_all_sales', 'Can view all sales')]},
        ),
    ]
