"""Validate a PostgreSQL database loaded from a Django JSON fixture."""

import json
from decimal import Decimal
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.db import connection
from django.apps import apps


class Command(BaseCommand):
    help = "Compare the current database with a dumpdata fixture."

    def add_arguments(self, parser):
        parser.add_argument(
            "fixture",
            type=Path,
            help="Path to the JSON file generated by dumpdata.",
        )

    def handle(self, *args, **options):
        fixture_path = options["fixture"]
        if not fixture_path.is_file():
            raise CommandError(f"No existe el fixture: {fixture_path}")

        try:
            with fixture_path.open("r", encoding="utf-8") as fixture_file:
                objects = json.load(fixture_file)
        except (OSError, json.JSONDecodeError) as exc:
            raise CommandError(f"No se pudo leer el fixture: {exc}") from exc

        if not isinstance(objects, list):
            raise CommandError("El fixture debe contener una lista JSON.")

        expected_counts = {}
        for item in objects:
            label = item.get("model")
            if not label or "pk" not in item:
                raise CommandError("Cada objeto debe tener model y pk.")
            expected_counts[label] = expected_counts.get(label, 0) + 1

        errors = []
        for label, expected_count in sorted(expected_counts.items()):
            try:
                model = apps.get_model(label)
            except LookupError:
                errors.append(f"Modelo desconocido en fixture: {label}")
                continue

            actual_count = model.objects.using("default").count()
            if actual_count != expected_count:
                errors.append(
                    f"{label}: fixture={expected_count}, base={actual_count}"
                )

        self._validate_products(objects, errors)
        self._validate_relations(errors)
        self._validate_sequences(errors)

        if errors:
            for error in errors:
                self.stderr.write(self.style.ERROR(f"ERROR: {error}"))
            raise CommandError(f"Migración inválida: {len(errors)} comprobación(es) fallaron.")

        self.stdout.write(self.style.SUCCESS(
            f"Migración válida: {len(objects)} objetos verificados, "
            "relaciones y secuencias correctas."
        ))

    def _validate_products(self, objects, errors):
        product_model = apps.get_model("Stock", "Producto")
        for item in objects:
            if item.get("model") != "Stock.producto":
                continue

            fields = item.get("fields", {})
            try:
                product = product_model.objects.using("default").get(pk=item["pk"])
            except product_model.DoesNotExist:
                errors.append(f"Stock.producto pk={item['pk']} no existe en la base")
                continue

            expected_price = Decimal(str(fields["precio"]))
            if product.precio != expected_price:
                errors.append(
                    f"Producto {product.pk}: precio fixture={expected_price}, "
                    f"base={product.precio}"
                )

            expected_stock = int(fields["stock"])
            if product.stock != expected_stock:
                errors.append(
                    f"Producto {product.pk}: stock fixture={expected_stock}, "
                    f"base={product.stock}"
                )

    def _validate_relations(self, errors):
        checks = (
            ("Stock", "Producto", "categoria", "Categoria"),
            ("ventas", "Venta", "cliente", "Cliente"),
            ("ventas", "Venta", "vendedor", "Perfil"),
            ("ventas", "Detalle_venta", "venta", "Venta"),
            ("ventas", "Detalle_venta", "producto", "Producto"),
            ("Stock", "MovimientosStock", "producto", "Producto"),
        )
        for app_label, model_name, field_name, related_model in checks:
            model = apps.get_model(app_label, model_name)
            field = model._meta.get_field(field_name)
            invalid = model.objects.using("default").filter(
                **{f"{field_name}__isnull": True}
            ).count()
            if invalid:
                errors.append(
                    f"{app_label}.{model_name}.{field_name}: {invalid} relaciones nulas"
                )

    def _validate_sequences(self, errors):
        if connection.vendor != "postgresql":
            return

        models_to_check = (
            apps.get_model("account", "Perfil"),
            apps.get_model("Stock", "Categoria"),
            apps.get_model("Stock", "Proveedor"),
            apps.get_model("Stock", "Estanteria"),
            apps.get_model("Stock", "Producto"),
            apps.get_model("Stock", "MovimientosStock"),
            apps.get_model("ventas", "Cliente"),
            apps.get_model("ventas", "Venta"),
            apps.get_model("ventas", "Detalle_venta"),
        )

        with connection.cursor() as cursor:
            for model in models_to_check:
                table_name = model._meta.db_table
                pk_column = model._meta.pk.column
                cursor.execute(
                    "SELECT pg_get_serial_sequence(%s, %s), "
                    f"MAX(\"{pk_column}\") FROM \"{table_name}\"",
                    [table_name, pk_column],
                )
                sequence_name, max_id = cursor.fetchone()
                if not sequence_name or max_id is None:
                    continue

                cursor.execute(
                    "SELECT last_value FROM "
                    f'"{sequence_name.split(".")[-1]}"'
                )
                last_value = cursor.fetchone()[0]
                if last_value < max_id:
                    errors.append(
                        f"Secuencia de {table_name} ({last_value}) por debajo "
                        f"del máximo ID ({max_id})"
                    )