# Generated by Django 6.0.3 on 2026-09-26 19:23

from django.db import migrations, models


def crear_empresa_inicial(apps, schema_editor):
    Empresa = apps.get_model('main', 'Empresa')
    Empresa.objects.get_or_create(
        slug='empresa-principal',
        defaults={'nombre': 'Empresa principal'},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.RunPython(crear_empresa_inicial, migrations.RunPython.noop),
    ]
