# Generated by Django 6.0.3 on 2026-09-26 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_price_changed', 'Modificación de precio'), ('sale_cancelled', 'Cancelación de venta'), ('credit_note_issued', 'Emisión de nota de crédito')], max_length=40)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.empresa')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['empresa', 'action', 'created_at'], name='main_audite_empresa_09995e_idx')],
            },
        ),
    ]
